// AUTO-GENERATED by bun scripts/build-lesson-manifest.mjs.
// Do not edit manually.

export type LessonManifestEntry = {
  id: string;
  metaFile: string;
  fps: number;
  width: number;
  height: number;
  durationInFrames: number;
};

export const lessonManifest: LessonManifestEntry[] = [
  {
    "id": "intro-stablecoin-landscape",
    "metaFile": "course-1-stablecoin-protocol/unit-1-background-foundations/1-intro-defi-landscape/source/lesson.meta.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 181
  },
  {
    "id": "what-is-prediction-market-v2",
    "metaFile": "course-4-prediction-market/unit-1-prediction-market-fundamentals/1-whta-is-prediction-market-v2/source/lesson.meta.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 5909
  },
  {
    "id": "what-is-prediction-market",
    "metaFile": "course-4-prediction-market/unit-1-prediction-market-fundamentals/1-whta-is-prediction-market/source/lesson.meta.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 5283
  },
  {
    "id": "prediction-market-curriculum-overview",
    "metaFile": "course-4-prediction-market/unit-1-prediction-market-fundamentals/curriculum-overview/source/lesson.meta.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 6613
  },
  {
    "id": "l1-protocol-revenue-token-demand-decoupling",
    "metaFile": "course-tokenomics/unit-1-tokenomics-1/1-protocol-revenue-and-token-demand-decoupling/source/lesson.meta.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 181
  },
  {
    "id": "demo-lesson-visual",
    "metaFile": "demo-course-visual/demo-unit/demo-lesson-visual/source/lesson.meta.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 5976
  },
  {
    "id": "demo-lesson-all-formats",
    "metaFile": "demo-course/demo-unit/demo-lesson-all-formats/source/lesson.meta.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 181
  },
  {
    "id": "demo-lesson-all-formats-zh",
    "metaFile": "demo-course/demo-unit/demo-lesson-all-formats/source/lesson.meta.zh.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 181
  }
];
