// AUTO-GENERATED by bun scripts/build-lesson-manifest.mjs.
// Do not edit manually.

export type LessonManifestEntry = {
  id: string;
  metaFile: string;
  fps: number;
  width: number;
  height: number;
  durationInFrames: number;
};

export const lessonManifest: LessonManifestEntry[] = [
  {
    "id": "intro-stablecoin-landscape",
    "metaFile": "course-1-stablecoin-protocol/unit-1-background-foundations/1-intro-defi-landscape/source/lesson.meta.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 17047
  },
  {
    "id": "l1-protocol-revenue-token-demand-decoupling",
    "metaFile": "course-tokenomics/unit-1-tokenomics-1/1-protocol-revenue-and-token-demand-decoupling/source/lesson.meta.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 9463
  },
  {
    "id": "demo-lesson-all-formats",
    "metaFile": "demo-course/demo-unit/demo-lesson-all-formats/source/lesson.meta.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 9619
  },
  {
    "id": "demo-lesson-all-formats-zh",
    "metaFile": "demo-course/demo-unit/demo-lesson-all-formats/source/lesson.meta.zh.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 3025
  }
];
