// AUTO-GENERATED by bun scripts/build-lesson-manifest.mjs.
// Do not edit manually.

export type LessonManifestEntry = {
  id: string;
  metaFile: string;
  fps: number;
  width: number;
  height: number;
  durationInFrames: number;
};

export const lessonManifest: LessonManifestEntry[] = [
  {
    "id": "defi-landscape",
    "metaFile": "course-1-stablecoin-protocol/unit-1-background-foundations/1-defi-landscape/source/lesson.meta.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 181
  },
  {
    "id": "prediction-market-curriculum-overview",
    "metaFile": "course-4-prediction-market/unit-1-prediction-market-fundamentals/curriculum-overview/source/lesson.meta.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 6613
  },
  {
    "id": "demo-lesson-all-formats",
    "metaFile": "demo-course/demo-unit/demo-lesson-all-formats/source/lesson.meta.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 181
  },
  {
    "id": "demo-lesson-all-formats-zh",
    "metaFile": "demo-course/demo-unit/demo-lesson-all-formats/source/lesson.meta.zh.json",
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 181
  }
];
