export const tokens = {
  colors: {
    bg: '#FFFFFF',
    text: '#0B0B0B',
    label: '#555555',
    bodyText: '#1A1A1A',
    muted: '#6B6B6B',
    panel: '#FFFFFF',
    panelSoft: 'rgba(255, 255, 255, 0.92)',
    border: '#000000',
    borderSoft: 'rgba(0, 0, 0, 0.12)',
    shadow: 'transparent',
    accent: '#FFE866',
    accentSoft: 'rgba(255, 232, 102, 0.35)',
    grid: 'rgba(0, 0, 0, 0.05)',
  },
  space: {
    xs: 8,
    sm: 12,
    md: 18,
    lg: 26,
    xl: 36,
  },
  radii: {
    sm: 12,
    md: 18,
    lg: 32,
    pill: 999,
  },
  stroke: {
    hairline: 1,
    regular: 2,
    strong: 3,
  },
  shadow: {
    card: 'none',
    overlay: 'none',
  },
  layout: {
    maxContentWidth: 1440,
  },
  storyboard: {
    canvasPadding: 96,
    codeBlock: {
      borderRadius: 20,
      headerPadY: 18,
      headerPadX: 20,
      headerFontSize: 24,
      bodyPadY: 20,
      linePadY: 6,
      linePadX: 20,
      lineNumberColWidth: 88,
      lineNumberFontSize: 26,
      codeFontSize: 26,
    },
    slide: {
      panelMaxWidth: 1440,
      panelPadY: 36,
      panelPadX: 48,
      panelRadius: 28,
      panelGridGap: 28,
      titleSize: 66,
      subtitleSize: 30,
      tableHeaderSize: 16,
      tableBodySize: 23,
      bodySize: 26,
      bulletSize: 28,
      fallbackKickerSize: 22,
      fallbackBodySize: 30,
    },
    explain: {
      gap: 24,
      listGap: 16,
      bodySize: 40,
      bodyLineHeight: 1.3,
    },
    fireText: {
      heroSize: 80,
      titleSize: 56,
      bodySize: 40,
      lineGap: 24,
      defaultWordInterval: 0.08,
    },
    chart: {
      panelMaxWidth: 1440,
      panelPadY: 36,
      panelPadX: 48,
      panelRadius: 28,
      eyebrowSize: 14,
      eyebrowMarginBottom: 12,
      titleSize: 66,
      titleMarginBottom: 22,
      titleLineHeight: 1.08,
      defaultWidth: 1360,
      defaultHeight: 620,
      columnGap: 22,
      minBarHeight: 10,
      barRadius: 16,
      labelSize: 24,
      labelLineHeight: 1.2,
    },
  },
} as const;
